// Builds index.html from layout.html and one HTML file per page section.
//
//   node build.js           build once
//   node build.js --watch   rebuild on every save (for previewing locally)
//
// layout.html holds the page shell (head, navbar, footer). Each line like
//   <!-- @include sections/experience/experience.html -->
// is replaced by that file. GitHub runs this on every push
// (.github/workflows/deploy.yml), so index.html is never edited or committed.
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const LAYOUT = path.join(ROOT, "layout.html");
const OUT = path.join(ROOT, "index.html");
const INCLUDE = /^([ \t]*)<!-- @include (\S+) -->[ \t]*$/gm;

const BANNER =
  "<!-- GENERATED by build.js from layout.html + sections/*/*.html.\n" +
  "     Do not edit this file: change layout.html or a section's .html instead. -->";

function build() {
  const layout = fs.readFileSync(LAYOUT, "utf8").replace(/\r\n/g, "\n");
  const used = [];
  let html = layout.replace(INCLUDE, (_, indent, file) => {
    const full = path.join(ROOT, file);
    // stay inside the repo, and stop the build rather than ship a hole
    if (!full.startsWith(ROOT + path.sep)) throw new Error(`include outside the site: ${file}`);
    if (!fs.existsSync(full)) throw new Error(`layout.html includes a missing file: ${file}`);
    used.push(file);
    return fs.readFileSync(full, "utf8").replace(/\r\n/g, "\n").trimEnd();
  });
  if (!html.startsWith("<!DOCTYPE html>")) throw new Error("layout.html must start with <!DOCTYPE html>");
  html = html.replace("<!DOCTYPE html>", `<!DOCTYPE html>\n${BANNER}`);
  fs.writeFileSync(OUT, html.replace(/\n/g, "\r\n"));
  console.log(`built index.html from layout.html + ${used.length} sections (${used.map((f) => path.basename(f, ".html")).join(", ")})`);
}

build();

if (process.argv.includes("--watch")) {
  const targets = [LAYOUT, path.join(ROOT, "sections")];
  let timer = null;
  for (const t of targets) {
    fs.watch(t, { recursive: true }, (_, file) => {
      if (file && !String(file).endsWith(".html") && t !== LAYOUT) return;
      clearTimeout(timer);
      timer = setTimeout(() => {
        try {
          build();
        } catch (e) {
          console.error("build failed:", e.message);
        }
      }, 100);
    });
  }
  console.log("watching layout.html and sections/**/*.html — Ctrl+C to stop");
}
