// Regenerates the bot's knowledge from knowledge/*.md:
//   knowledge/profile.md + knowledge/faq.md  ->  knowledge.js             (the page's FAQ fallback)
//                                            ->  worker/src/knowledge.js  (the AI's record)
// Each folder in knowledge/projects/ (e.g. projects/sleepalarm/) adds its own
// profile.md and faq.md in the same formats, appended after the main ones.
// Run after editing any .md file:   node chatbot/build.js
// Then redeploy the Worker so the AI sees the change:   cd chatbot/worker && npx wrangler deploy
const fs = require("fs");
const path = require("path");

const HERE = __dirname;
const read = (p) => fs.readFileSync(p, "utf8").replace(/\r\n/g, "\n");
const stripComments = (s) => s.replace(/<!--[\s\S]*?-->/g, "");

// ---- profile.md: "## Title {#anchor}" sections ----
function parseProfile(md) {
  const out = [];
  for (const block of stripComments(md).split(/^## /m).slice(1)) {
    const [head, ...body] = block.split("\n");
    const m = head.match(/^(.+?)\s*\{#([\w-]+)\}\s*$/);
    if (!m) throw new Error(`profile.md: heading needs an {#anchor}: "${head}"`);
    out.push({ title: m[1].trim(), anchor: m[2], text: body.join("\n").trim() });
  }
  return out;
}

// ---- faq.md: "## id", "keywords:", "sources:", answer ----
function parseFaq(md, titles) {
  const out = [];
  for (const block of stripComments(md).split(/^## /m).slice(1)) {
    const lines = block.split("\n");
    const id = lines.shift().trim();
    let keywords = [];
    let sources = [];
    const rest = [];
    for (const line of lines) {
      if (/^keywords:/i.test(line)) keywords = line.replace(/^keywords:/i, "").split(",").map((s) => s.trim()).filter(Boolean);
      else if (/^sources:/i.test(line)) sources = line.replace(/^sources:/i, "").split(",").map((s) => s.trim()).filter((s) => s && s.toLowerCase() !== "none");
      else rest.push(line);
    }
    for (const s of sources) if (!titles.includes(s)) throw new Error(`faq.md [${id}]: unknown source "${s}"`);
    if (!keywords.length) throw new Error(`faq.md [${id}]: no keywords`);
    const answer = rest.join(" ").replace(/\s+/g, " ").trim();
    out.push({ id, keywords, sources, answer, todo: answer === "TODO" || !answer });
  }
  return out;
}

// the main record first, then one folder per project under knowledge/projects/
const PROJECTS = path.join(HERE, "knowledge", "projects");
const dirs = [
  path.join(HERE, "knowledge"),
  ...(fs.existsSync(PROJECTS)
    ? fs.readdirSync(PROJECTS, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => path.join(PROJECTS, d.name)).sort()
    : []),
];
const readIf = (p) => (fs.existsSync(p) ? read(p) : "");

const sections = dirs.flatMap((d) => parseProfile(readIf(path.join(d, "profile.md"))));
const titles = sections.map((s) => s.title);
const faq = dirs.flatMap((d) => parseFaq(readIf(path.join(d, "faq.md")), titles));

const dupe = (list) => list.find((x, i) => list.indexOf(x) !== i);
if (dupe(titles)) throw new Error(`two profile sections are titled "${dupe(titles)}"`);
if (dupe(faq.map((f) => f.id))) throw new Error(`two faq entries use the id "${dupe(faq.map((f) => f.id))}"`);
const email = (sections.find((s) => s.anchor === "contact").text.match(/[\w.+-]+@[\w-]+(?:\.[\w-]+)+/) || [])[0];
if (!email) throw new Error("no email in the Contact section");

const knowledge = JSON.stringify({ email, sections, faq }, null, 2);
const banner = "// Generated by chatbot/build.js from knowledge/*.md. Do not edit by hand.\n";
fs.writeFileSync(path.join(HERE, "knowledge.js"), `${banner}window.PUNITBOT_KNOWLEDGE = ${knowledge};\n`);
fs.writeFileSync(path.join(HERE, "worker", "src", "knowledge.js"), `${banner}export default ${knowledge};\n`);

const todo = faq.filter((f) => f.todo).map((f) => f.id);
console.log(`sections: ${titles.join(", ")}`);
console.log(`faq: ${faq.length} entries${todo.length ? `, still TODO: ${todo.join(", ")}` : ", all answered"}`);
console.log("wrote chatbot/knowledge.js and chatbot/worker/src/knowledge.js");
console.log("next: cd chatbot/worker && npx wrangler deploy");
